apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd-operator.fullname" . }}-proxy
  labels:
  {{- include "etcd-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
  {{- include "etcd-operator.selectorLabels" . | nindent 4 }}
    component: proxy
