---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "etcd-operator.fullname" . }}-leader-election-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "etcd-operator.fullname" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "etcd-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "etcd-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "etcd-operator.fullname" . }}-manager-role
rules:
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - persistantvolumeclaims/status
    verbs:
      - create
      - get
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdbackups
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdbackups/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdbackupschedules
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdbackupschedules/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdclusters
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdpeers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdpeers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdrestores
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - etcd.improbable.io
    resources:
      - etcdrestores/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ include "etcd-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "etcd-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
