apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd-operator.fullname" . }}-webhook
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
  {{- include "etcd-operator.selectorLabels" . | nindent 4 }}
    component: manager

