name: CI
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Need all the history for git describe --tags to work
          fetch-depth: 0
      - uses: actions/setup-go@v2
          with:
            go-version: '^1.16.0'
      - name: Install kubectl
        run: |
            # Download & verify kubectl
            curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubectl
            echo "3ff48e12f9c768ad548e4221d805281ea28dfcda5c18b3cd1797fe37aee3012e  kubectl" | sha256sum -c
            # Mark it executable & move to /bin
            sudo chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin
      - name: End to end tests
        run: make e2e-kind