name: Release Docker images
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Need all the history for git describe --tags to work
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - name: Install buildx
        run: |
          sudo apt-get update
          sudo apt-get install -y binfmt-support qemu-user-static jq
          mkdir -p ~/.docker/cli-plugins
          BUILDX_URL=$(curl https://api.github.com/repos/docker/buildx/releases/latest | jq -r .assets[].browser_download_url | grep amd64 | grep linux)
          wget $BUILDX_URL -O ~/.docker/cli-plugins/docker-buildx
          chmod +x ~/.docker/cli-plugins/docker-buildx
          docker buildx create --name xbuilder
          docker buildx use xbuilder
          docker buildx inspect --bootstrap
      - name: Login to registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build and push Docker image
        run: make docker-push
